# Credenciales de tu proyecto en SonarCloud
sonar.organization=mvtnight
sonar.projectKey=mvtnight_IngDevops

# Información del proyecto
sonar.projectName=Microservicio Hola Mundo DevOps
sonar.projectVersion=1.0

# Dónde buscar el código fuente (el punto significa "en esta carpeta")
sonar.sources=.
# Excluir la carpeta de GitHub de los análisis
sonar.exclusions=**/.github/**, **/tests/**

# Ruta del reporte de cobertura de pruebas (Vital para el IE3 y IE6)
sonar.python.coverage.reportPaths=coverage.xml